version: "3"
services:
  trekapi_server:
    container_name: trekapi_server
    build: .
    env_file:
      - .env
    command: "just serve"
    ports:
      - "5007:5007"
    networks:
      - trekapi_network
      - nginx_network
    restart: always
  trekapi_db:
    container_name: trekapi_db
    image: "postgres:13.3"
    env_file: .env
    command: -p 5433
    ports:
      - 5433:5433
    volumes:
      - ~/trekapi-data:/var/lib/postgresql/data
    networks:
      - trekapi_network
    restart: always

networks:
  nginx_network:
    external:
      name: nginx_default
  trekapi_network: ~
