version: "3"
services:
  trekapi_server:
    container_name: trekapi_server
    build: .
    env_file:
      - .env
    command: "just serve"
    ports:
      - "5007:5007"
    volumes:
      - /var/lib/trekapi/data:/var/lib/trekapi/data
    networks:
      - nginx_network

  trekapi_scheduler:
    container_name: trekapi_scheduler
    build: .
    env_file:
      - .env
    command: "just schedule"
    volumes:
      - /var/lib/trekapi/data:/var/lib/trekapi/data
    restart: always

networks:
  nginx_network:
    external:
      name: nginx_default
